import type { Metadata } from "next"
import "@fontsource-variable/geist"
import "./globals.css"
import Header from "@/components/layout/Header"
import Banner from "@/components/layout/Banner"
import Footer from "@/components/layout/Footer"
import { fetchGlobalData } from "@/lib/strapi"
import { AOSInitializer } from "@/components/AOSInitializer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const globalData = await fetchGlobalData()

  return (
    <html lang="es">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </head>
      <body>
        <AOSInitializer />
        <Banner data={globalData.banner} />
        <Header data={globalData.header} />
        {children}
        <Footer data={globalData.footer} />
        <script async defer src="https://app.chatby.io/js/widget/nhxhsg85lwry0ujm/float.js"></script>
      </body>
    </html>
  )
}
